### PR TITLE
TypeScript Milestone - WIP

### PR DESCRIPTION
**Pull request by prestonvanloon**

### CODE REVIEW

**Comment by prestonvanloon** [comment]
@DanBotero Looks like you are taking over TypeScript stuff. Please resolve the conflicts on this branch & merge or discard these changes.

**Comment by kirjs** [comment]
Is this relevant?

**Comment by prestonvanloon** [comment]
@kirjs Dan took over what I was working on, but I don't know if he used any of this. I assigned to @DanBotero.

**Comment by kirjs** [comment]
Looks like it's all merged in, closing

**Pull request closed without merging**
